os: linux

dist: trusty
jdk: oraclejdk8

env:
  global:
    - FLUTTER_HOME=/home/travis/flutter

language: android

android:
  components:
    - tools
    - android-28
    - build-tools-28.0.3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lib32stdc++6
      - libstdc++6
      - curl

cache:
  directories:
    - $HOME/.pub-cache

before_script:
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1 $FLUTTER_HOME
  - export PATH=${FLUTTER_HOME}/bin:${FLUTTER_HOME}/bin/cache/dart-sdk/bin:$PATH

script:
  - flutter doctor -v
  - flutter analyze
  - flutter build appbundle
