name: flutter_reddit_app
description: Simple passive Reddit client

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reddit:
    git:
      url: git://github.com/veikkos/dart-reddit.git
      ref: fix-array-decode
  flutter_linkify: ^2.1.0
  url_launcher : ^5.4.1
  cupertino_icons: ^0.1.2
  flutter_typeahead: ^1.7.0
  html_unescape: ^1.0.1+3
  flutter_markdown: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "icon/icon.png"
  android: "launcher_icon"
  ios: true
